name = "dry_eye_api"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Set these in the Cloudflare dashboard or via wrangler secret put
# GOOGLE_CLIENT_ID = ""
# GOOGLE_CLIENT_SECRET = ""
# JWT_SECRET = ""
FRONTEND_URL = "https://dry-eye-web.ronymateo.workers.dev/"

[[d1_databases]]
binding = "DB"
database_name = "weqe-db"
database_id = "025e31c9-e68c-49e5-ad71-724b3b882663"
migrations_dir = "migrations"

[dev]
port = 8787
